### ISSUE TITLE
Multimedia content is not appearing in the webapp

### ISSUE THREAD

**Issue by kulas** [CMP-Studio/WebGuideApp#2]
There should be an embedded video as part of this stop and it is not appearing.
http://guide.carnegiemuseums.org/collections/iris-van-herpen-transforming-fashion/t/iris-van-herpen-transforming-fashion/5001-crystallization-skirt-top

**Comment by RubenSandwich** [comment]
@drewmcd621 Can you look into this one?

**Comment by drewmcd621** [comment]
Hi Neil,

Videos are currently not supported on the web guide.
